Ilham/Ilham/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Ilham import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ilham/account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views


app_name = "account"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreation.as_view(), name='registration'),
    # path('change_password/', ),
]

Ilham/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('performer/', views.PerformersView.as_view(), name='performer'),
    path('library/', views.LibraryView.as_view(), name='library'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
]

Ilham/templates/includes/aside.html
<div class="aside">
    <h3>Исполнители которых мы советуем послушать</h3>
    <div class="performers">
        {% for performer in performers %}
            <a href="">
                <div class="performers-card">
                    <img src="{{ performer.performer_img.url }}"
                     alt="{{ performer.performer_img.name }}">
                    <p>{{ performer.performer_name }}</p>
                </div>
            </a>
        {% endfor %}
    </div>
</div>

Ilham/templates/includes/header.html
{% load static %}

<header>
    <nav class="navigation">
        <ul class="menu">
            <li><a href="{% url 'home' %}"><img src="{% static 'main/img/logo.png' %}" alt="logo"></a></li>
            <li><a href="{% url 'home' %}">Главная</a></li>
            <li><a href="{% url 'library' %}">Моя библиотека</a></li>
        </ul>
        <ul class="account">
            <li>
                <form class="search" action="{% url 'search_results' %}" method="get">
                    <input class="search-input" name="q" type="text" placeholder="Поиск">
                    <button class="search-btn" type="submit"></button>
                </form>
            </li>
            {% if user.is_authenticated %}
                <form action="{% url 'account:logout' %}" method="post">{% csrf_token %}
                    <button class="btn" type="submit">Выйти из аккаунта</button>
                </form>
            {% else %}
                <li><a class="btn" href="{% url 'account:login' %}">Войти</a></li>
                <li><a class="btn" href="{% url 'account:registration' %}">Регистрация</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

Ilham/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
    <article class="content">
        <ul class="paginator">
            {% if page_obj.has_previous %}
                <li><a href="?q={{ query }}&page={{ page_obj.previous_page_number }}">◁</a></li>
            {% endif %}

            {% for foo in paginator.page_range %}
                {% if page_obj.number == foo %}
                    <li class="current"><p>{{ foo }}</p></li>
                {% elif foo >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                {% else %}
                    <li><a href="?q={{ query }}&page={{ foo }}">{{ foo }}</a></li>
                {% endif %}

            {% endfor %}

            {% if page_obj.has_next %}
                <li><a href="?q={{ query }}&page={{ page_obj.next_page_number }}">▷</a></li>
            {% endif %}
        </ul>
    </article>

{% endif %}

Ilham/templates/includes/releases.html
<div class="release-list">
    {% for release in releases %}
        <a class="track" href="">
            <div class="hidden-overlay">
                Играть
            </div>
            <div class="release-card">
                <div class="picture">
                    <img src="{{ release.track_img.url }}" alt="{{ release.track_img.name }}">
                </div>

                <p>{{ release.track_name }}</p>
                <p>{{ release.performer }}</p>
                <p>{{ release.genre }}</p>
            </div>
        </a>
    {% endfor %}
</div>
{% include 'includes/paginator.html' %}